### DELETE ALL RECIPES
DELETE http://localhost:3001/api/development/recipes

### DELETE RECIPE BY ID
DELETE http://localhost:3001/api/development/recipes/1

### DELETE ALL USERS
DELETE http://localhost:3001/api/development/users

### DELETE USER BY ID
DELETE http://localhost:3001/api/development/users/1

### UPDATE PERMISSION OF USER BY ID
PATCH http://localhost:3001/api/development/permissions/1
Content-Type: application/json

{
    "permission": [
        {"role": "admin"}
    ]
}
