POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "username": "JabberJerry",
    "email": "test@cool.com",
    "password": "password"
}

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "JabberJerry",
    "password": "password"
}

###

POST http://localhost:3000/auth/logout

###

GET http://localhost:3000/testing/authorized
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJKYWJiZXJKZXJyeSIsImlhdCI6MTY4MDMwNzg4MCwiZXhwIjoxNjgwMzA3OTEwfQ.eZR8vZ8_gDhFcMsv1OUj13twTtP9GuZCbHNjyGx_gp8