GET http://localhost:3000/users

###

GET http://localhost:3000/users/63eac52bf1c62dc4bb5429f1

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "3",
    "email": "3@4.com",
    "password": "password"
}

###

DELETE http://localhost:3000/users/63eac22376e533542f98044c

###

PATCH http://localhost:3000/users/63eac52bf1c62dc4bb5429f1
Content-Type: application/json

{
    "username": "JibberJerry"
}