POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "username": "JabberJerry",
    "email": "test@cool.com",
    "password": "password"
}

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "name": "test@cool.com",
    "password": "password"
}

###

GET http://localhost:3000/endpoint/authorized
Content-Type: application/json
Authorization: Bearer ayJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2M2VkYjMxNWQ1MGU5Mjk5YThmM2U4ZDQiLCJ1c2VyRW1haWwiOiJ0ZXN0QGNvb2wuY29tIiwidXNlck5hbWUiOiJKYWJiZXJKZXJyeSIsImlhdCI6MTY3NjUyMzkzMCwiZXhwIjoxNjc5MTE1OTMwfQ.mY_9o5xE2bp1AgozKNpsFUb61ScCAANGm14eeMkft-4