### GET ALL RECIPES
GET http://localhost:3001/api/recipes

### CREATE RECIPE
POST http://localhost:3001/api/recipes
Content-Type: application/json
//Authorization: Bearer WRITE_TOKEN_HERE

{
    "title": "Chocolate Milk",
    //"image": "ImageBlob!",
    "time": "00:01:00",
    "ingredients": "1 cup milk:4 Tbsp chocolate syrup",
    //"tags": "1:2:3:4",
    "steps": "Pour milk in a glass:Add chocolate syrup to glass:Stir for 30 seconds or until mixed",
    "description": "Delicious choclate milk, the way Grandma made it!"
}